import test from "node:test";
import assert from "node:assert/strict";
import { buildMemoryReminder, memoryInjectMessage, shouldInject } from "../lib/inject.js";

test("reminder includes both scopes and forbids rereading MEMORY.md", () => {
  const text = buildMemoryReminder({
    globalManifest: "# Global memory index\n\n- Preferences (`topics/preferences.md`)\n",
    workspaceManifest: "# Workspace memory index\n\n- Testing (`topics/testing.md`)\n",
    globalDir: "/tmp/jiyi/global",
    workspaceDir: "/tmp/jiyi/workspaces/app-1",
  });
  assert.match(text, /<system-reminder>/);
  assert.match(text, /不要读、不要改 MEMORY.md/);
  assert.match(text, /jiyi_list/);
  assert.match(text, /jiyi_read/);
  assert.match(text, /只读/);
  assert.match(text, /禁止 create、edit、delete/);
  assert.match(text, /topics\/testing.md/);
  assert.match(text, /\/tmp\/jiyi\/global/);
  assert.match(text, /Read-only root/);
});

test("empty manifests skip injection", () => {
  assert.equal(buildMemoryReminder({ globalManifest: "", workspaceManifest: "" }), null);
  assert.equal(buildMemoryReminder({
    globalManifest: "# Global memory index\n\nGenerated by jiyi. Do not edit this file directly.\n\nNo topics yet.\n",
    workspaceManifest: "# Workspace memory index\n\nNo topics yet.\n",
    globalDir: "/tmp/jiyi/global",
    workspaceDir: "/tmp/jiyi/workspaces/app-1",
  }), null);
});

test("inject message is plugin-sourced", () => {
  const message = memoryInjectMessage("hello");
  assert.equal(message.role, "user");
  assert.equal(message.source.plugin, "jiyi");
  assert.equal(message.content[0].text, "hello");
});

test("shouldInject waits for first real batch", () => {
  assert.equal(shouldInject({ kind: "reject" }, 1, false), false);
  assert.equal(shouldInject({ kind: "enter", messages: [] }, 1, false), false);
  assert.equal(shouldInject({ kind: "enter", messages: [] }, 5, false), false);
  assert.equal(shouldInject({ kind: "enter", messages: [{ id: "1" }] }, 1, false), true);
  assert.equal(shouldInject({ kind: "enter", messages: [{ id: "1" }] }, 1, true), false);
});
