import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import * as path from "node:path";
import { listEntries, remember } from "../lib/storage.js";
import { matchTopic, registerMemoryTools, searchTopics, summarizeTopics } from "../lib/tools.js";

const TEST_CWD = "/Users/ning/.dsh/jiyi-test-workspace";

async function seededStore() {
  const root = await mkdtemp(path.join(tmpdir(), "jiyi-"));
  await remember(root, TEST_CWD, null, { text: "use just test", topicHint: "testing" });
  const listed = await listEntries(root, TEST_CWD, null);
  const wsDir = path.dirname(listed.entries.find((item) => item.scope === "workspace" && item.group === "index").path);
  await mkdir(path.join(wsDir, "topics"), { recursive: true });
  await writeFile(path.join(wsDir, "topics", "testing.md"), "# Testing\n\n- use just test\n");
  return { root, listed: await listEntries(root, TEST_CWD, null) };
}

test("matchTopic accepts slug, relative path, and title", async () => {
  const { listed } = await seededStore();
  assert.equal(matchTopic(listed.entries, "testing").hit.relative, "topics/testing.md");
  assert.equal(matchTopic(listed.entries, "topics/testing.md").hit.relative, "topics/testing.md");
  assert.equal(matchTopic(listed.entries, "Testing").hit.relative, "topics/testing.md");
  assert.equal(matchTopic(listed.entries, "MEMORY.md").hit, null);
  assert.equal(matchTopic(listed.entries, listed.entries.find((item) => item.group === "index").path).hit, null);
});

test("summarizeTopics is read-only metadata", async () => {
  const { listed } = await seededStore();
  const summary = summarizeTopics(listed);
  assert.equal(summary.topics.length, 1);
  assert.equal(summary.topics[0].relative, "topics/testing.md");
  assert.equal(summary.inbox, 1);
});

test("searchTopics matches content and ignores MEMORY.md", async () => {
  const { root, listed } = await seededStore();
  const hits = await searchTopics(root, listed, "just test");
  assert.equal(hits.length, 1);
  assert.match(hits[0].snippet, /just test/);
  assert.equal((await searchTopics(root, listed, "Generated by jiyi")).length, 0);
});

test("list renderer still shows inbox when there are no topics", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "jiyi-"));
  await remember(root, TEST_CWD, null, { text: "use just test", topicHint: "testing" });
  const registered = [];
  registerMemoryTools({
    tools: { register(tool) { registered.push(tool); } },
  }, {
    root,
    cwdOf: () => TEST_CWD,
    originOf: async () => null,
  });
  const listed = await registered[0].execute({}, { agent: {} });
  const rendered = registered[0].output.render({}, listed);
  assert.match(rendered[0].text, /No jiyi topics yet/);
  assert.match(rendered[0].text, /Inbox: 1/);
});

test("matchTopic requires scope when global and workspace share a slug", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "jiyi-"));
  await remember(root, TEST_CWD, null, { text: "workspace fact", topicHint: "same" });
  const listed0 = await listEntries(root, TEST_CWD, null);
  const wsDir = path.dirname(listed0.entries.find((item) => item.scope === "workspace" && item.group === "index").path);
  await mkdir(path.join(wsDir, "topics"), { recursive: true });
  await mkdir(path.join(root, "global", "topics"), { recursive: true });
  await writeFile(path.join(wsDir, "topics", "same.md"), "# Same\n\nworkspace\n");
  await writeFile(path.join(root, "global", "topics", "same.md"), "# Same\n\nglobal\n");
  const listed = await listEntries(root, TEST_CWD, null);
  const ambiguous = matchTopic(listed.entries, "same");
  assert.equal(ambiguous.ambiguous, true);
  assert.equal(matchTopic(listed.entries, "same", "workspace").hit.scope, "workspace");
  assert.equal(matchTopic(listed.entries, "global:same").hit.scope, "global");
});

test("registerMemoryTools exposes list/read/search and refuses MEMORY.md", async () => {
  const { root } = await seededStore();
  const registered = [];
  registerMemoryTools({
    tools: { register(tool) { registered.push(tool); } },
  }, {
    root,
    cwdOf: () => TEST_CWD,
    originOf: async () => null,
  });
  assert.deepEqual(registered.map((tool) => tool.name), ["jiyi_list", "jiyi_read", "jiyi_search"]);
  const exec = { agent: {} };
  const listed = await registered[0].execute({}, exec);
  assert.equal(listed.topics.length, 1);
  const read = await registered[1].execute({ path: "testing" }, exec);
  assert.match(read.content, /just test/);
  await assert.rejects(() => registered[1].execute({ path: "MEMORY.md" }, exec), /unknown topic/);
  const search = await registered[2].execute({ query: "just" }, exec);
  assert.equal(search.hits.length, 1);
});
